#!/usr/bin/env python3
"""Generate one complete native gameplay descriptor bundle from HORO_BEHAVIOR annotations."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


ANNOTATION = re.compile(
    r"\bHORO_BEHAVIOR\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*\"([^\"]+)\"\s*\)"
)
TYPE_ID = re.compile(r"game\.[a-z0-9_]+(?:\.[a-z0-9_]+)+\Z")


def parse() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--module-id", required=True)
    parser.add_argument("--fingerprint", required=True)
    parser.add_argument("sources", nargs="+", type=pathlib.Path)
    return parser.parse_args()


def main() -> int:
    args = parse()
    annotations: list[tuple[str, str, pathlib.Path]] = []
    for source in args.sources:
        text = source.read_text(encoding="utf-8")
        annotations.extend((symbol, type_id, source) for symbol, type_id in ANNOTATION.findall(text))

    seen_symbols: set[str] = set()
    seen_ids: set[str] = set()
    for symbol, type_id, source in annotations:
        if symbol in seen_symbols:
            raise ValueError(f"duplicate native behavior symbol {symbol!r} in {source}")
        if type_id in seen_ids:
            raise ValueError(f"duplicate native behavior type ID {type_id!r} in {source}")
        if not TYPE_ID.fullmatch(type_id):
            raise ValueError(f"invalid native behavior type ID {type_id!r} in {source}")
        seen_symbols.add(symbol)
        seen_ids.add(type_id)

    declarations = "\n".join(
        f"Horo::Gameplay::BehaviorRegistration HoroGeneratedBehaviorRegistration_{symbol}();"
        for symbol, _, _ in annotations
    )
    initializers = ",\n        ".join(
        f"HoroGeneratedBehaviorRegistration_{symbol}()" for symbol, _, _ in annotations
    )
    count = len(annotations)
    output = f'''// Generated by generate_gameplay_behavior_bundle.py. Do not edit.
#include "Horo/Gameplay/GameModule.h"
#include <array>

{declarations}

namespace {{
const auto &Registrations() {{
    static const std::array<Horo::Gameplay::BehaviorRegistration, {count}> registrations{{{{
        {initializers}
    }}}};
    return registrations;
}}
}}

extern "C" HORO_GAME_EXPORT const Horo::Gameplay::GameModuleDescriptor *GetGameModuleDescriptor() noexcept {{
    static const Horo::Gameplay::GameModuleDescriptor descriptor{{
        sizeof(Horo::Gameplay::GameModuleDescriptor), Horo::Gameplay::GameplaySdkBoundaryVersion,
        "{args.module_id}", "{args.fingerprint}"}};
    return &descriptor;
}}

extern "C" HORO_GAME_EXPORT const Horo::Gameplay::GeneratedGameplayDescriptorBundle *GetGameplayDescriptorBundle() noexcept {{
    static const Horo::Gameplay::GeneratedGameplayDescriptorBundle bundle{{
        sizeof(Horo::Gameplay::GeneratedGameplayDescriptorBundle), "{args.module_id}", "{args.fingerprint}", 1,
        Registrations().data(), Registrations().size()}};
    return &bundle;
}}
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"gameplay descriptor generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
