#!/usr/bin/env python3
"""parse_changelog.py — Build-time CHANGELOG.md parser for Horo Engine.

Reads CHANGELOG.md (Keep-a-Changelog format) and emits GeneratedBuildInfo.h
with the two most recent release entries baked in as constexpr C++ data.

Usage:
    python3 parse_changelog.py <changelog_path> <output_header_path>
"""

import re
import sys
import os
import textwrap

# ---------------------------------------------------------------------------
# Format contract
#   ## [x.y.z] — YYYY-MM-DD        <- section header  (required)
#   ### Added / Fixed / Changed      <- sub-section     (optional)
#   - First bullet text              <- body source      (first bullet used)
# ---------------------------------------------------------------------------

MAX_ENTRIES = 2
MAX_BODY_CHARS = 120


def _escape_cpp(s: str) -> str:
    """Escape a string for use as a C++ string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _truncate(s: str, limit: int = MAX_BODY_CHARS) -> str:
    if len(s) <= limit:
        return s
    return s[:limit].rstrip() + "\u2026"  # ellipsis


def parse_changelog(text: str) -> list[dict]:
    """Return up to MAX_ENTRIES dicts with keys: tag, title, body."""
    # Split on level-2 headers: ## [version] — date  (or ## [Unreleased])
    sections = re.split(r"(?m)^(?=## \[)", text)

    entries = []
    for section in sections:
        header_match = re.match(
            r"## \[([^\]]+)\](?:\s*[—\-–]\s*(\d{4}-\d{2}-\d{2}))?", section
        )
        if not header_match:
            continue

        version_str = header_match.group(1)
        date_str = header_match.group(2) or ""

        # Skip [Unreleased] blocks — they have no shipped content yet
        if version_str.lower() == "unreleased":
            continue

        # Build the title
        if date_str:
            # Reformat YYYY-MM-DD to "Month YYYY" for display
            parts = date_str.split("-")
            months = [
                "", "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            ]
            try:
                month_name = months[int(parts[1])]
                title = f"v{version_str} — {month_name} {parts[0]}"
            except (IndexError, ValueError):
                title = f"v{version_str} — {date_str}"
        else:
            title = f"v{version_str}"

        # Extract the first bullet under any ### sub-section
        body = ""
        bullet_match = re.search(r"^- (.+)$", section, re.MULTILINE)
        if bullet_match:
            body = _truncate(bullet_match.group(1).strip())

        entries.append({"tag": "Release Notes", "title": title, "body": body})
        if len(entries) >= MAX_ENTRIES:
            break

    return entries


FALLBACK = [
    {"tag": "Release Notes", "title": "No releases yet", "body": ""},
    {"tag": "Release Notes", "title": "No releases yet", "body": ""},
]


def render_header(entries: list[dict]) -> str:
    # Pad to exactly MAX_ENTRIES
    padded = (entries + FALLBACK)[:MAX_ENTRIES]

    lines = [
        "// This file is AUTO-GENERATED by scripts/parse_changelog.py",
        "// DO NOT EDIT — changes will be overwritten on the next CMake configure.",
        "// Source: CHANGELOG.md",
        "#pragma once",
        "",
        "namespace Horo::Generated {",
        "",
        "/** @brief A single 'What\\'s New' card entry baked in at build time. */",
        "struct WhatsNewEntry {",
        "    const char* tag;   ///< Card category label (e.g. \"Release Notes\")",
        "    const char* title; ///< Card headline",
        "    const char* body;  ///< Short description (max ~120 chars)",
        "};",
        "",
        f"/** @brief Number of valid What's New entries (always {MAX_ENTRIES}). */",
        f"inline constexpr int kWhatsNewCount = {MAX_ENTRIES};",
        "",
        f"/** @brief What's New entries generated from CHANGELOG.md. */",
        f"inline constexpr WhatsNewEntry kWhatsNewEntries[{MAX_ENTRIES}] = {{",
    ]

    for i, e in enumerate(padded):
        comma = "," if i < MAX_ENTRIES - 1 else ""
        tag = _escape_cpp(e["tag"])
        title = _escape_cpp(e["title"])
        body = _escape_cpp(e["body"])
        lines.append(f'    {{"{tag}", "{title}", "{body}"}}{comma}')

    lines += [
        "};",
        "",
        "} // namespace Horo::Generated",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(
            f"Usage: {sys.argv[0]} <changelog_path> <output_header_path>",
            file=sys.stderr,
        )
        return 1

    changelog_path = sys.argv[1]
    output_path = sys.argv[2]

    if os.path.isfile(changelog_path):
        with open(changelog_path, encoding="utf-8") as f:
            text = f.read()
        entries = parse_changelog(text)
    else:
        print(
            f"[parse_changelog] WARNING: '{changelog_path}' not found — using fallback.",
            file=sys.stderr,
        )
        entries = []

    header = render_header(entries)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(
        f"[parse_changelog] Generated {output_path} with {len(entries)} entr{'y' if len(entries) == 1 else 'ies'}.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
