#!/usr/bin/env python3
"""Build-time CHANGELOG.md parser for Horo Engine."""

import re
import sys
from pathlib import Path

MAX_ENTRIES = 2
MAX_BODY_CHARS = 120
RELEASE_NOTES_TAG = "Release Notes"


def _escape_cpp(value: str) -> str:
    """Escape a string for use as a C++ string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _truncate(value: str, limit: int = MAX_BODY_CHARS) -> str:
    if len(value) <= limit:
        return value
    return value[:limit].rstrip() + "\u2026"


def _release_title(version: str, date: str) -> str:
    if not date:
        return f"v{version}"
    year, month, _day = date.split("-")
    months = (
        "", "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    )
    try:
        return f"v{version} — {months[int(month)]} {year}"
    except (IndexError, ValueError):
        return f"v{version} — {date}"


def parse_changelog(text: str) -> list[dict]:
    """Return up to MAX_ENTRIES dictionaries with tag, title, and body."""
    sections = re.split(r"(?m)^(?=## \[)", text)
    entries = []
    for section in sections:
        header_match = re.match(
            r"## \[([^\]]+)\](?:\s*[—\-–]\s*(\d{4}-\d{2}-\d{2}))?", section
        )
        if not header_match:
            continue

        version, date = header_match.group(1), header_match.group(2) or ""
        if version.lower() == "unreleased":
            continue

        bullet_match = re.search(r"^- (.+)$", section, re.MULTILINE)
        body = _truncate(bullet_match.group(1).strip()) if bullet_match else ""
        entries.append({
            "tag": RELEASE_NOTES_TAG,
            "title": _release_title(version, date),
            "body": body,
        })
        if len(entries) >= MAX_ENTRIES:
            break
    return entries


FALLBACK = [
    {"tag": RELEASE_NOTES_TAG, "title": "No releases yet", "body": ""},
    {"tag": RELEASE_NOTES_TAG, "title": "No releases yet", "body": ""},
]


def render_header(entries: list[dict]) -> str:
    """Render the generated C++ header."""
    padded = (entries + FALLBACK)[:MAX_ENTRIES]
    lines = [
        "// This file is AUTO-GENERATED by scripts/parse_changelog.py",
        "// DO NOT EDIT — changes will be overwritten on the next CMake configure.",
        "// Source: CHANGELOG.md",
        "#pragma once",
        "",
        "namespace Horo::Generated {",
        "",
        "/** @brief A single 'What's New' card entry baked in at build time. */",
        "struct WhatsNewEntry {",
        "    const char* tag;   ///< Card category label (e.g. \"Release Notes\")",
        "    const char* title; ///< Card headline",
        "    const char* body;  ///< Short description (max ~120 chars)",
        "};",
        "",
        "/** @brief Number of valid What's New entries (always 2). */",
        f"inline constexpr int kWhatsNewCount = {MAX_ENTRIES};",
        "/** @brief What's New entries generated from CHANGELOG.md. */",
        f"inline constexpr WhatsNewEntry kWhatsNewEntries[{MAX_ENTRIES}] = {{",
    ]
    for index, entry in enumerate(padded):
        comma = "," if index < MAX_ENTRIES - 1 else ""
        lines.append(
            f'    {{"{_escape_cpp(entry["tag"])}", '
            f'"{_escape_cpp(entry["title"])}", '
            f'"{_escape_cpp(entry["body"])}"}}{comma}'
        )
    lines += ["};", "", "} // namespace Horo::Generated", ""]
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <changelog_path> <output_header_path>", file=sys.stderr)
        return 1

    changelog_path = Path(sys.argv[1]).expanduser()
    output_path = Path(sys.argv[2]).expanduser()
    if any(part == ".." for part in changelog_path.parts + output_path.parts):
        print("[parse_changelog] Refusing paths containing '..'.", file=sys.stderr)
        return 1

    if changelog_path.is_file():
        with changelog_path.open(encoding="utf-8") as changelog_file:
            entries = parse_changelog(changelog_file.read())
    else:
        print(f"[parse_changelog] WARNING: '{changelog_path}' not found — using fallback.", file=sys.stderr)
        entries = []

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as output_file:
        output_file.write(render_header(entries))

    count_word = "entry" if len(entries) == 1 else "entries"
    print(f"[parse_changelog] Generated {output_path} with {len(entries)} {count_word}.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
