/**
 * @file IconsFontAwesome6.h
 * @brief Font Awesome 6 icon glyph constants for use with ImGui.
 *
 * This file is auto-generated.  Each `ICON_FA_*` constant is a UTF-8
 * encoded string containing the Unicode code point for the corresponding
 * Font Awesome 6 Free glyph.  Pass these strings directly to ImGui text
 * functions or as button labels.
 *
 * @note Do not edit this file manually; regenerate it from the Font Awesome
 *       icon metadata when updating the icon font version.
 */
#pragma once

// FontAwesome 6 Free - Solid Icons
// Usage: ImGui::Text(ICON_FA_PLAY); or ImGui::Button(ICON_FA_PLAY)

constexpr unsigned int ICON_MIN_FA = 0xe000;
constexpr unsigned int ICON_MAX_FA = 0xf8ff;

// Toolbar Icons
constexpr const char* ICON_FA_MOUSE_POINTER = "\xef\x89\x85";             // Select
constexpr const char* ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT = "\xef\x81\x87"; // Move/Translate
constexpr const char* ICON_FA_ROTATE = "\xef\x8b\xb9";                    // Rotate
constexpr const char* ICON_FA_EXPAND = "\xef\x81\xa5";                    // Scale
constexpr const char* ICON_FA_PLAY = "\xef\x81\x8b";                      // Play
constexpr const char* ICON_FA_PAUSE = "\xef\x81\x8c";                     // Pause
constexpr const char* ICON_FA_STOP = "\xef\x81\x8d";                      // Stop
constexpr const char* ICON_FA_GEAR = "\xef\x80\x93";                      // Settings
constexpr const char* ICON_FA_CIRCLE_QUESTION = "\xef\x81\x99";           // Help
constexpr const char* ICON_FA_CHEVRON_DOWN = "\xef\x81\xb8";              // Dropdown arrow
constexpr const char* ICON_FA_FOLDER = "\xef\x81\xbb";                    // Scene/Folder
constexpr const char* ICON_FA_SLIDERS = "\xef\x87\x9e";                   // Preset
constexpr const char* ICON_FA_MAGNIFYING_GLASS = "\xef\x80\x82";          // Search
constexpr const char* ICON_FA_FILTER = "\xef\x82\xb0";                    // Filter
constexpr const char* ICON_FA_ELLIPSIS_VERTICAL = "\xef\x85\x82";         // More
constexpr const char* ICON_FA_CARET_DOWN = "\xef\x83\x97";                // Expanded tree item
constexpr const char* ICON_FA_CARET_RIGHT = "\xef\x83\x9a";               // Collapsed tree item
constexpr const char* ICON_FA_SUN = "\xef\x86\x85";                       // Directional light

// Other useful icons
constexpr const char* ICON_FA_PLUS = "\xef\x81\x95";                      // Add
constexpr const char* ICON_FA_MINUS = "\xef\x81\xa8";                     // Remove
constexpr const char* ICON_FA_TRASH = "\xef\x87\xb8";                     // Delete
constexpr const char* ICON_FA_COPY = "\xef\x83\x85";                      // Copy
constexpr const char* ICON_FA_PASTE = "\xef\x83\xaa";                     // Paste
constexpr const char* ICON_FA_UNDO = "\xef\x83\xa2";                      // Undo
constexpr const char* ICON_FA_REDO = "\xef\x80\x9e";                      // Redo
constexpr const char* ICON_FA_SAVE = "\xef\x83\x87";                      // Save
constexpr const char* ICON_FA_FOLDER_OPEN = "\xef\x81\xbc";               // Open
constexpr const char* ICON_FA_FILE = "\xef\x85\x9b";                      // New File
constexpr const char* ICON_FA_EYE = "\xef\x81\xae";                       // View
constexpr const char* ICON_FA_CUBE = "\xef\x86\xb2";                      // 3D Object
constexpr const char* ICON_FA_LIGHTBULB = "\xef\x83\xab";                 // Light
constexpr const char* ICON_FA_VIDEO = "\xef\x80\xbd";                     // Camera
constexpr const char* ICON_FA_HAND_POINTER = "\xef\x89\x9b";              // Selection
constexpr const char* ICON_FA_XMARK = "\xef\x80\x8d";                     // Clear/Close
